@extends('platform.admin.layouts.app')
@section('title', 'Exchange Pairs | LonePawn Admin')
@section('pageTitle', 'Default Exchange Pairs')
@section('pageDescription', 'Define explicit base and quote directions available to tenants.')
@section('content')
<div class="content-stack admin-exchange-pair-page">
    @if ($errors->any())<div class="flash error" role="alert">{{ $errors->first() }}</div>@endif
    <section class="content-card admin-finance-create-card"><div class="admin-section-heading"><div><p class="admin-section-kicker">Rate direction</p><h2>Add pair</h2><p>Choose the base and quote currencies for tenant exchange rates.</p></div></div><form method="POST" action="{{ route('admin.exchange-pairs.store') }}" class="filter-grid">@csrf<label>Base<select name="base_currency_code">@foreach($currencies as $currency)<option value="{{ $currency->code }}" @selected(old('base_currency_code') === $currency->code)>{{ $currency->code }}</option>@endforeach</select></label><label>Quote<select name="quote_currency_code">@foreach($currencies as $currency)<option value="{{ $currency->code }}" @selected(old('quote_currency_code') === $currency->code)>{{ $currency->code }}</option>@endforeach</select></label><div class="admin-finance-create-actions"><button type="submit" class="button primary">Create pair</button></div></form></section>
    <section class="content-card admin-finance-list-card"><div class="admin-section-heading"><div><p class="admin-section-kicker">Global defaults</p><h2>Pair catalog</h2><p>{{ $pairs->total() }} configured exchange pairs.</p></div></div>
        <div class="admin-finance-desktop"><div class="table-wrap"><table><thead><tr><th>Pair</th><th>Meaning</th><th>State</th><th>Actions</th></tr></thead><tbody>@forelse($pairs as $pair)<tr><td><strong>{{ $pair->baseCurrency->code }}/{{ $pair->quoteCurrency->code }}</strong></td><td>1 {{ $pair->baseCurrency->code }} = rate × {{ $pair->quoteCurrency->code }}</td><td><span class="badge" data-tone="{{ $pair->is_active ? 'success' : 'warning' }}">{{ $pair->is_active ? 'Active' : 'Inactive' }}</span></td><td><div class="action-row"><button type="button" class="button secondary" data-open-dialog="pair-edit-{{ $pair->id }}">Edit</button><button type="button" class="button danger" data-open-dialog="pair-delete-{{ $pair->id }}">Delete</button></div></td></tr>@empty<tr><td colspan="4">No pairs.</td></tr>@endforelse</tbody></table></div></div>
        <div class="admin-finance-mobile">@forelse($pairs as $pair)<article class="admin-finance-mobile-card"><div><p class="admin-section-kicker">Exchange pair</p><h3>{{ $pair->baseCurrency->code }}/{{ $pair->quoteCurrency->code }}</h3><p>1 {{ $pair->baseCurrency->code }} = rate × {{ $pair->quoteCurrency->code }}</p></div><span class="badge" data-tone="{{ $pair->is_active ? 'success' : 'warning' }}">{{ $pair->is_active ? 'Active' : 'Inactive' }}</span><div class="admin-finance-mobile-actions"><button type="button" class="button secondary" data-open-dialog="pair-edit-{{ $pair->id }}">Edit</button><button type="button" class="button danger" data-open-dialog="pair-delete-{{ $pair->id }}">Delete</button></div></article>@empty<p>No pairs.</p>@endforelse</div>
        {{ $pairs->links() }}
    </section>
</div>
@foreach($pairs as $pair)
<dialog class="platform-dialog admin-finance-dialog" id="pair-edit-{{ $pair->id }}"><form method="POST" action="{{ route('admin.exchange-pairs.update', $pair) }}">@csrf @method('PUT')<input type="hidden" name="dialog_id" value="pair-edit-{{ $pair->id }}"><input type="hidden" name="update_key" value="{{ $pair->update_key }}"><input type="hidden" name="base_currency_code" value="{{ $pair->baseCurrency->code }}"><input type="hidden" name="quote_currency_code" value="{{ $pair->quoteCurrency->code }}"><div class="dialog-header"><h2>Edit {{ $pair->baseCurrency->code }}/{{ $pair->quoteCurrency->code }}</h2><button type="button" class="dialog-close" data-close-dialog="pair-edit-{{ $pair->id }}">&times;</button></div><p>Enable or disable this pair for tenant use.</p><label class="admin-check-row"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($pair->is_active)> Active</label><div class="action-row admin-dialog-actions"><button type="button" class="button secondary" data-close-dialog="pair-edit-{{ $pair->id }}">Cancel</button><button type="submit" class="button primary">Save changes</button></div></form></dialog>
<dialog class="platform-dialog admin-finance-dialog" id="pair-delete-{{ $pair->id }}"><form method="POST" action="{{ route('admin.exchange-pairs.destroy', $pair) }}">@csrf @method('DELETE')<div class="dialog-header"><h2>Delete {{ $pair->baseCurrency->code }}/{{ $pair->quoteCurrency->code }}?</h2><button type="button" class="dialog-close" data-close-dialog="pair-delete-{{ $pair->id }}">&times;</button></div><p>This action is only allowed when no exchange rates reference the pair.</p><div class="action-row admin-dialog-actions"><button type="button" class="button secondary" data-close-dialog="pair-delete-{{ $pair->id }}">Cancel</button><button type="submit" class="button danger">Delete pair</button></div></form></dialog>
@endforeach
@include('platform.admin.partials.finance-dialog-script')
@endsection
