@extends('platform.admin.layouts.app')
@section('title', 'Exchange Rates | LonePawn Admin')
@section('pageTitle', 'Platform Exchange Rates')
@section('pageDescription', 'Record sequential observations. Corrections preserve the original history.')
@section('content')
<div class="content-stack">@if ($errors->any())<div class="flash error">{{ $errors->first() }}</div>@endif
<section class="content-card"><h2>Record rate</h2><form method="POST" action="{{ route('admin.exchange-rates.store') }}" class="filter-grid">@csrf<label>Pair<select name="pair_code">@foreach($pairs as $pair)<option value="{{ $pair->code }}">{{ $pair->baseCurrency->code }}/{{ $pair->quoteCurrency->code }}</option>@endforeach</select></label><label>Rate<input name="rate" inputmode="decimal" required></label><label>Observed at<input name="observed_at" type="datetime-local"></label><button class="primary-button">Record rate</button></form></section>
<section class="content-card"><h2>Rate observations</h2><div class="table-wrap"><table><thead><tr><th>Pair</th><th>Rate</th><th>Observed</th><th>Status</th><th>Correction</th></tr></thead><tbody>
@forelse($rates as $rate)<tr><td>{{ $rate->pair->baseCurrency->code }}/{{ $rate->pair->quoteCurrency->code }}</td><td>{{ $rate->rate }}</td><td>{{ $rate->observed_at }}</td><td>{{ $rate->is_void ? 'Void' : 'Active' }}</td><td>@unless($rate->is_void)<form method="POST" action="{{ route('admin.exchange-rates.correct', $rate) }}" class="inline-form">@csrf<input name="rate" placeholder="Replacement rate" required><input name="reason" placeholder="Correction reason" required><button>Correct</button></form><form method="POST" action="{{ route('admin.exchange-rates.void', $rate) }}" class="inline-form">@csrf<input name="reason" placeholder="Void reason" required><button class="danger-button">Void</button></form>@endunless</td></tr>@empty<tr><td colspan="5">No rates.</td></tr>@endforelse
</tbody></table></div>{{ $rates->links() }}</section></div>
<section class="content-card"><h2>Daily OHLC</h2><div class="table-wrap"><table><thead><tr><th>Date</th><th>Pair</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Entries</th></tr></thead><tbody>@forelse($dailySummaries as $summary)<tr><td>{{ $summary->rate_date->toDateString() }}</td><td>{{ $summary->pair->baseCurrency->code }}/{{ $summary->pair->quoteCurrency->code }}</td><td>{{ $summary->open_rate }}</td><td>{{ $summary->high_rate }}</td><td>{{ $summary->low_rate }}</td><td>{{ $summary->close_rate }}</td><td>{{ $summary->entry_count }}</td></tr>@empty<tr><td colspan="7">No daily summaries.</td></tr>@endforelse</tbody></table></div>{{ $dailySummaries->links() }}</section>
@endsection
