@extends('platform.admin.layouts.app')
@section('title', 'Exchange Rates | LonePawn Admin')
@section('pageTitle', 'Platform Exchange Rates')
@section('pageDescription', 'Record buying and selling observations. Corrections preserve the original history.')
@section('content')
<div class="content-stack admin-exchange-rate-page">
    @if ($errors->any())<div class="flash error admin-finance-page-error" role="alert">{{ $errors->first() }}</div>@endif
    <section class="content-card admin-finance-create-card"><div class="admin-section-heading"><div><p class="admin-section-kicker">Current observation</p><h2>Record current prices</h2><p>Publish a buying and selling observation for an active pair.</p></div></div><form method="POST" action="{{ route('admin.exchange-rates.store') }}" class="filter-grid">@csrf<label>Pair<select name="pair_code">@foreach($pairs as $pair)<option value="{{ $pair->code }}" @selected(old('pair_code') === $pair->code)>{{ $pair->baseCurrency->code }}/{{ $pair->quoteCurrency->code }}</option>@endforeach</select></label><label>Buying price<input name="buying_rate" inputmode="decimal" value="{{ old('buying_rate') }}" required></label><label>Selling price<input name="selling_rate" inputmode="decimal" value="{{ old('selling_rate') }}" required></label><div class="admin-finance-create-actions"><button type="submit" class="button primary">Record prices</button></div></form></section>
    <section class="content-card admin-finance-list-card"><div class="admin-section-heading"><div><p class="admin-section-kicker">Immutable history</p><h2>Rate observations</h2><p>Correct or void an observation while retaining its original record.</p></div></div>
        <div class="admin-finance-desktop"><div class="table-wrap"><table><thead><tr><th>Pair</th><th>Buying</th><th>Selling</th><th>Observed</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($rates as $rate)<tr><td>{{ $rate->pair->baseCurrency->code }}/{{ $rate->pair->quoteCurrency->code }}</td><td>{{ $rate->buying_rate }}</td><td>{{ $rate->selling_rate }}</td><td>{{ $rate->observed_at }}</td><td><span class="badge" data-tone="{{ $rate->is_void ? 'danger' : 'success' }}">{{ $rate->is_void ? 'Void' : 'Active' }}</span></td><td><div class="action-row">@if($rate->can_correct)<button type="button" class="button secondary" data-open-dialog="rate-correct-{{ $rate->id }}">Correct</button>@endif @if($rate->can_void)<button type="button" class="button danger" data-open-dialog="rate-void-{{ $rate->id }}">Void</button>@endif</div></td></tr>@empty<tr><td colspan="6">No rates.</td></tr>@endforelse</tbody></table></div></div>
        <div class="admin-finance-mobile">@forelse($rates as $rate)<article class="admin-finance-mobile-card"><div><p class="admin-section-kicker">{{ $rate->pair->baseCurrency->code }}/{{ $rate->pair->quoteCurrency->code }}</p><h3>{{ $rate->buying_rate }} / {{ $rate->selling_rate }}</h3><p>{{ $rate->observed_at }}</p></div><span class="badge" data-tone="{{ $rate->is_void ? 'danger' : 'success' }}">{{ $rate->is_void ? 'Void' : 'Active' }}</span><div class="admin-finance-mobile-actions">@if($rate->can_correct)<button type="button" class="button secondary" data-open-dialog="rate-correct-{{ $rate->id }}">Correct</button>@endif @if($rate->can_void)<button type="button" class="button danger" data-open-dialog="rate-void-{{ $rate->id }}">Void</button>@endif</div></article>@empty<p>No rates.</p>@endforelse</div>
        {{ $rates->links() }}
    </section>
    <section class="content-card admin-finance-list-card admin-exchange-rate-chart-card">
        <div class="admin-section-heading">
            <div><p class="admin-section-kicker">Daily closing trend</p><h2>{{ $selectedPair ? $selectedPair->baseCurrency->code.'/'.$selectedPair->quoteCurrency->code : 'Currency pair' }} closing prices</h2><p>Compare platform buying and selling closes for the selected period.</p></div>
        </div>
        <form method="GET" action="{{ route('admin.exchange-rates.index') }}" class="admin-exchange-rate-chart-filters">
            <label>Currency pair<select name="pair_code" onchange="this.form.submit()">@foreach($pairs as $pair)<option value="{{ $pair->code }}" @selected($selectedPair?->id === $pair->id)>{{ $pair->baseCurrency->code }}/{{ $pair->quoteCurrency->code }}</option>@endforeach</select></label>
            <fieldset><legend>Period</legend><div class="admin-exchange-rate-range">@foreach([7, 30, 90] as $range)<button type="submit" class="button {{ $trendDays === $range ? 'primary' : 'secondary' }}" name="days" value="{{ $range }}" aria-pressed="{{ $trendDays === $range ? 'true' : 'false' }}">{{ $range }}D</button>@endforeach</div></fieldset>
        </form>
        @if(count($trend))
            <div class="admin-exchange-rate-chart"><canvas data-admin-exchange-rate-chart aria-label="Buying and selling closing-price trend for {{ $selectedPair->baseCurrency->code }}/{{ $selectedPair->quoteCurrency->code }}" role="img"></canvas></div>
            <script type="application/json" id="admin-exchange-rate-chart-data">{!! json_encode(['points' => $trend], JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
        @else
            <div class="empty-state"><p>No closing prices were recorded for this currency pair during the selected period.</p></div>
        @endif
    </section>
</div>
@foreach($rates as $rate)
@if($rate->can_correct)<dialog class="platform-dialog admin-finance-dialog" id="rate-correct-{{ $rate->id }}"><form method="POST" action="{{ route('admin.exchange-rates.correct', $rate) }}">@csrf<input type="hidden" name="dialog_id" value="rate-correct-{{ $rate->id }}"><div class="dialog-header"><h2>Correct exchange rate</h2><button type="button" class="dialog-close" data-close-dialog="rate-correct-{{ $rate->id }}">&times;</button></div><div class="form-grid"><label>Buying price<input name="buying_rate" inputmode="decimal" required></label><label>Selling price<input name="selling_rate" inputmode="decimal" required></label><label class="form-grid-wide">Correction reason<textarea name="reason" rows="3" required></textarea></label></div><div class="action-row admin-dialog-actions"><button type="button" class="button secondary" data-close-dialog="rate-correct-{{ $rate->id }}">Cancel</button><button type="submit" class="button primary">Save correction</button></div></form></dialog>@endif
@if($rate->can_void)<dialog class="platform-dialog admin-finance-dialog" id="rate-void-{{ $rate->id }}"><form method="POST" action="{{ route('admin.exchange-rates.void', $rate) }}">@csrf<input type="hidden" name="dialog_id" value="rate-void-{{ $rate->id }}"><div class="dialog-header"><h2>Void exchange rate?</h2><button type="button" class="dialog-close" data-close-dialog="rate-void-{{ $rate->id }}">&times;</button></div><label>Void reason<textarea name="reason" rows="3" required></textarea></label><div class="action-row admin-dialog-actions"><button type="button" class="button secondary" data-close-dialog="rate-void-{{ $rate->id }}">Cancel</button><button type="submit" class="button danger">Void rate</button></div></form></dialog>@endif
@endforeach
@include('platform.admin.partials.finance-dialog-script')
@endsection
