<?php

return [
    'prefixes' => [
        'manual_payment_attachments' => 'MA',
        'manual_payment_requests' => 'MP',
        'pawn_collateral_items' => 'CI',
        'pawn_loan_contract_slips' => 'LS',
        'platform_users' => 'PU',
        'platform_support_ticket_attachments' => 'TA',
        'platform_support_tickets' => 'ST',
        'tenant_customers' => 'TC',
        'tenant_debts' => 'DB',
        'tenant_lenders' => 'LD',
        'tenant_business_loans' => 'BL',
        'tenant_business_loan_payments' => 'BP',
        'tenant_expenses' => 'EX',
        'tenant_scheduled_expenses' => 'SE',
        'tenant_requests' => 'TR',
        'tenant_users' => 'TU',
        'financial_accounts' => 'FA',
        'catalog_items' => 'CAT',
        'inventory_items' => 'II',
        'inventory_locations' => 'IL',
        'inventory_units' => 'IU',
        'inventory_movements' => 'IM',
        'owned_items' => 'OI',
        'acquisition_lots' => 'AL',
        'ownership_movements' => 'OM',
        'purchase_suppliers' => 'PS',
        'purchase_orders' => 'PO',
        'purchase_order_lines' => 'PL',
        'purchase_payments' => 'PP',
        'purchase_refunds' => 'PR',
        'purchase_receipts' => 'RC',
        'purchase_receipt_lines' => 'RL',
        'purchase_returns' => 'RT',
        'purchase_return_lines' => 'RN',
    ],
];
