<?php

return [
    'features' => [
        'tenant_user_management' => [
            'name' => 'Tenant user management',
            'description' => 'Create, update, and remove tenant users.',
            'is_active' => true,
        ],
        'customer_management' => [
            'name' => 'Customer management',
            'description' => 'Create, update, and remove tenant customers.',
            'is_active' => true,
        ],
        'collateral_management' => [
            'name' => 'Collateral management',
            'description' => 'Create, update, and remove pawn collateral items.',
            'is_active' => true,
        ],
        'loan_contract_management' => [
            'name' => 'Loan contract management',
            'description' => 'Create, view, and delete pawn loan contract slips.',
            'is_active' => true,
        ],
        'interest_payment_management' => [
            'name' => 'Interest payment management',
            'description' => 'Calculate and receive loan contract interest payments.',
            'is_active' => true,
        ],
        'redemption_management' => [
            'name' => 'Redemption management',
            'description' => 'Calculate and process pawn redemptions.',
            'is_active' => true,
        ],
        'accounting_management' => [
            'name' => 'Accounting management',
            'description' => 'Manage tenant accounting records.',
            'is_active' => true,
        ],
        'expense_management' => [
            'name' => 'Expense management',
            'description' => 'Manage tenant expenses and linked accounting records.',
            'is_active' => true,
        ],
        'capital_management' => [
            'name' => 'Capital management',
            'description' => 'Manage tenant capital entries and linked accounting records.',
            'is_active' => true,
        ],
        'debt_management' => [
            'name' => 'Debt management',
            'description' => 'Manage tenant debt records.',
            'is_active' => true,
        ],
        'slip_document_preview' => [
            'name' => 'Slip document preview',
            'description' => 'Preview and download loan contract slip documents.',
            'is_active' => true,
        ],
        'slip_document_layout_management' => [
            'name' => 'Slip document layout management',
            'description' => 'Customize loan contract slip header and footer layouts.',
            'is_active' => false,
        ],
        'subdomain_available' => [
            'name' => 'Subdomain available',
            'description' => 'Allow tenant access through a dedicated subdomain.',
            'is_active' => true,
        ],
        'branding_management' => [
            'name' => 'Branding management',
            'description' => 'Customize tenant logo, favicon, colors, and branding text.',
            'is_active' => false,
        ],
        'master_data_management' => [
            'name' => 'Master data management',
            'description' => 'Manage tenant material, interest, expense, and financial account types.',
            'is_active' => true,
        ],
        'accounting_type_management' => [
            'name' => 'Accounting type management',
            'description' => 'Manage tenant-owned financial account types.',
            'is_active' => true,
        ],
        'multi_account_management' => [
            'name' => 'Multi-account management',
            'description' => 'Create, update, and manage multiple tenant financial accounts.',
            'is_active' => true,
        ],
        'dashboard' => [
            'name' => 'Summary Dashboard',
            'description' => 'View Detailed Summary in Dashboard',
            'is_active' => true,
        ],
        'currency_management' => [
            'name' => 'Currency management',
            'description' => 'Manage tenant currencies and currency preferences.',
            'is_active' => true,
        ],
        'exchange_pair_management' => [
            'name' => 'Exchange pair management',
            'description' => 'Manage tenant exchange-rate pairs.',
            'is_active' => true,
        ],
        'daily_rate_assignment' => [
            'name' => 'Daily rate assignment',
            'description' => 'Assign exchange rates and view daily rate history and trends.',
            'is_active' => true,
        ],
        'account_transferable' => [
            'name' => 'Account transferable',
            'description' => 'Transfer balances between tenant financial accounts.',
            'is_active' => true,
        ],
        'tenant_timezone_management' => [
            'name' => 'Tenant timezone management',
            'description' => 'Configure the tenant business timezone.',
            'is_active' => true,
        ],
        'automatic_open_close' => [
            'name' => 'Automatic accounting day open and close',
            'description' => 'Configure weekly accounting day opening and closing schedules.',
            'is_active' => true,
        ],
        'advanced_interest_process' => [
            'name' => 'Advanced interest process',
            'description' => 'Configure interest compounding and partial principal collection.',
            'is_active' => true,
        ],
    ],

    'packages' => [
        'trial' => [
            'name' => 'Trial',
            'description' => 'Trial package for evaluating the pawnshop system.',
            'price' => 0,
            'max_slip_per_month' => 30,
            'max_staff_count' => 2,
            'max_account_count' => 1,
            'max_currency_type_count' => 0,
            'max_exchange_pair_count' => 0,
            'is_active' => true,
            'features' => [
                'tenant_user_management',
                'customer_management',
                'collateral_management',
                'loan_contract_management',
                'interest_payment_management',
                'redemption_management',
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'slip_document_preview',
                'account_transferable',
                'multi_account_management',
            ],
        ],
        'basic' => [
            'name' => 'Basic',
            'description' => 'Basic package for growing pawnshops.',
            'price' => 50000,
            'max_slip_per_month' => 300,
            'max_staff_count' => 5,
            'max_account_count' => 2,
            'max_currency_type_count' => 3,
            'max_exchange_pair_count' => 3,
            'is_active' => true,
            'features' => [
                'tenant_user_management',
                'customer_management',
                'collateral_management',
                'loan_contract_management',
                'interest_payment_management',
                'redemption_management',
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'slip_document_preview',
                'master_data_management',
                'currency_management',
                'exchange_pair_management',
                'daily_rate_assignment',
                'account_transferable',
                'multi_account_management',
                'tenant_timezone_management',
                'dashboard',
            ],
        ],
        'premium' => [
            'name' => 'Premium',
            'description' => 'Premium package with branding and advanced features.',
            'price' => 100000,
            'max_slip_per_month' => 1000,
            'max_staff_count' => 10,
            'max_account_count' => 10,
            'max_currency_type_count' => 5,
            'max_exchange_pair_count' => 5,
            'is_active' => true,
            'features' => [
                'tenant_user_management',
                'customer_management',
                'collateral_management',
                'loan_contract_management',
                'interest_payment_management',
                'redemption_management',
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'slip_document_preview',
                'slip_document_layout_management',
                'master_data_management',
                'subdomain_available',
                'currency_management',
                'exchange_pair_management',
                'daily_rate_assignment',
                'account_transferable',
                'tenant_timezone_management',
                'automatic_open_close',
                'advanced_interest_process',
                'multi_account_management',
                'dashboard',
            ],
        ],
    ],

    'budgeting_packages' => [
        'budgeting-trial' => [
            'name' => 'Budgeting Trial',
            'description' => 'Trial package for evaluating budgeting and accounting features.',
            'price' => 0,
            'rank' => 0,
            'is_trial' => true,
            'is_active' => true,
            'max_slip_per_month' => 0,
            'max_staff_count' => 0,
            'max_account_count' => 1,
            'max_currency_type_count' => 0,
            'max_exchange_pair_count' => 0,
            'features' => [
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'account_transferable',
                'multi_account_management',
            ],
        ],
        'budgeting-basic' => [
            'name' => 'Budgeting Basic',
            'description' => 'Basic package for budgeting and accounting workflows.',
            'price' => 15000,
            'rank' => 100,
            'is_trial' => false,
            'is_active' => true,
            'max_slip_per_month' => 0,
            'max_staff_count' => 3,
            'max_account_count' => 3,
            'max_currency_type_count' => 2,
            'max_exchange_pair_count' => 2,
            'features' => [
                'master_data_management',
                'accounting_type_management',
                'tenant_timezone_management',
                'tenant_user_management',
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'account_transferable',
                'multi_account_management',
                'currency_management',
                'exchange_pair_management',
                'daily_rate_assignment',
                'dashboard',
            ],
        ],
        'budgeting-premium' => [
            'name' => 'Budgeting Premium',
            'description' => 'Premium package for unrestricted budgeting and accounting workflows.',
            'price' => 0,
            'rank' => 200,
            'is_trial' => false,
            'is_active' => false,
            'max_slip_per_month' => null,
            'max_staff_count' => null,
            'max_account_count' => null,
            'max_currency_type_count' => null,
            'max_exchange_pair_count' => null,
        ],
    ],
];
