<?php

return [
    'features' => [
        'tenant_user_management' => [
            'name' => 'Tenant user management',
            'description' => 'Create, update, and remove tenant users.',
        ],
        'customer_management' => [
            'name' => 'Customer management',
            'description' => 'Create, update, and remove tenant customers.',
        ],
        'collateral_management' => [
            'name' => 'Collateral management',
            'description' => 'Create, update, and remove pawn collateral items.',
        ],
        'loan_contract_management' => [
            'name' => 'Loan contract management',
            'description' => 'Create, view, and delete pawn loan contract slips.',
        ],
        'interest_payment_management' => [
            'name' => 'Interest payment management',
            'description' => 'Calculate and receive loan contract interest payments.',
        ],
        'redemption_management' => [
            'name' => 'Redemption management',
            'description' => 'Calculate and process pawn redemptions.',
        ],
        'accounting_management' => [
            'name' => 'Accounting management',
            'description' => 'Manage tenant accounting records.',
        ],
        'expense_management' => [
            'name' => 'Expense management',
            'description' => 'Manage tenant expenses and linked accounting records.',
        ],
        'capital_management' => [
            'name' => 'Capital management',
            'description' => 'Manage tenant capital entries and linked accounting records.',
        ],
        'debt_management' => [
            'name' => 'Debt management',
            'description' => 'Manage tenant debt records.',
        ],
        'slip_document_preview' => [
            'name' => 'Slip document preview',
            'description' => 'Preview and download loan contract slip documents.',
        ],
        'slip_document_layout_management' => [
            'name' => 'Slip document layout management',
            'description' => 'Customize loan contract slip header and footer layouts.',
        ],
        'subdomain_available' => [
            'name' => 'Subdomain available',
            'description' => 'Allow tenant access through a dedicated subdomain.',
        ],
        'branding_management' => [
            'name' => 'Branding management',
            'description' => 'Customize tenant logo, favicon, colors, and branding text.',
        ],
        'master_data_management' => [
            'name' => 'Master data management',
            'description' => 'Manage tenant material, interest, expense, and financial account types.',
        ],
        'accounting_type_management' => [
            'name' => 'Accounting type management',
            'description' => 'Manage tenant-owned financial account types.',
        ],
        'multi_account_management' => [
            'name' => 'Multi-account management',
            'description' => 'Create, update, and manage multiple tenant financial accounts.',
        ],
        'dashboard' => [
            'name' => 'Summary Dashboard',
            'description' => 'View Detailed Summary in Dashboard',
        ],
        'currency_exchange_management' => [
            'name' => 'Currency and exchange-rate management',
            'description' => 'Manage tenant currencies, exchange pairs, rates, and daily OHLC history.',
        ],
        'tenant_timezone_management' => [
            'name' => 'Tenant timezone management',
            'description' => 'Configure the tenant business timezone.',
        ],
    ],

    'packages' => [
        'trial' => [
            'name' => 'Trial',
            'description' => 'Trial package for evaluating the pawnshop system.',
            'price' => 0,
            'max_slip_per_month' => 30,
            'max_staff_count' => 2,
            'max_account_count' => 1,
            'max_currency_type_count' => 3,
            'max_exchange_pair_count' => 2,
            'is_active' => true,
            'features' => [
                'tenant_user_management',
                'customer_management',
                'collateral_management',
                'loan_contract_management',
                'interest_payment_management',
                'redemption_management',
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'slip_document_preview',
                'subdomain_available',
                'currency_exchange_management',
                'multi_account_management',
            ],
        ],
        'basic' => [
            'name' => 'Basic',
            'description' => 'Basic package for growing pawnshops.',
            'price' => 50000,
            'max_slip_per_month' => 300,
            'max_staff_count' => 5,
            'max_account_count' => 5,
            'max_currency_type_count' => 10,
            'max_exchange_pair_count' => 10,
            'is_active' => true,
            'features' => [
                'tenant_user_management',
                'customer_management',
                'collateral_management',
                'loan_contract_management',
                'interest_payment_management',
                'redemption_management',
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'slip_document_preview',
                'master_data_management',
                'subdomain_available',
                'currency_exchange_management',
                'multi_account_management',
            ],
        ],
        'premium' => [
            'name' => 'Premium',
            'description' => 'Premium package with branding and advanced features.',
            'price' => 100000,
            'max_slip_per_month' => null,
            'max_staff_count' => null,
            'max_account_count' => null,
            'max_currency_type_count' => null,
            'max_exchange_pair_count' => null,
            'is_active' => true,
            'features' => [
                'tenant_user_management',
                'customer_management',
                'collateral_management',
                'loan_contract_management',
                'interest_payment_management',
                'redemption_management',
                'accounting_management',
                'expense_management',
                'capital_management',
                'debt_management',
                'slip_document_preview',
                'slip_document_layout_management',
                'master_data_management',
                'subdomain_available',
                'currency_exchange_management',
                'tenant_timezone_management',
                'multi_account_management',
            ],
        ],
    ],

    'budgeting_packages' => [
        'budgeting-trial' => [
            'name' => 'Budgeting Trial',
            'description' => 'Trial package for evaluating budgeting and accounting features.',
            'price' => 0,
            'rank' => 0,
            'is_trial' => true,
            'is_active' => true,
            'max_slip_per_month' => null,
            'max_staff_count' => null,
            'max_account_count' => 1,
            'max_currency_type_count' => 3,
            'max_exchange_pair_count' => 2,
        ],
        'budgeting-basic' => [
            'name' => 'Budgeting Basic',
            'description' => 'Basic package for budgeting and accounting workflows.',
            'price' => 0,
            'rank' => 100,
            'is_trial' => false,
            'is_active' => false,
            'max_slip_per_month' => null,
            'max_staff_count' => null,
            'max_account_count' => 5,
            'max_currency_type_count' => 10,
            'max_exchange_pair_count' => 10,
        ],
        'budgeting-premium' => [
            'name' => 'Budgeting Premium',
            'description' => 'Premium package for unrestricted budgeting and accounting workflows.',
            'price' => 0,
            'rank' => 200,
            'is_trial' => false,
            'is_active' => false,
            'max_slip_per_month' => null,
            'max_staff_count' => null,
            'max_account_count' => null,
            'max_currency_type_count' => null,
            'max_exchange_pair_count' => null,
        ],
    ],
];
