<?php

return [
    'codes' => [
        'dashboard' => 'Allows viewing the tenant dashboard summary.',
        'access_all' => 'Full tenant access.',
        'list_user' => 'Allows viewing the tenant user list.',
        'create_user' => 'Allows creating tenant users.',
        'delete_user' => 'Allows flag-deleting tenant users.',
        'update_user_admin' => 'Allows updating tenant user role and status.',
        'update_user_all' => 'Allows updating any tenant user profile information.',
        'update_user_own' => 'Allows updating only own tenant user profile information.',
        'create_admin_user' => 'Allows creating tenant users with the Admin role.',
        'update_admin_user' => 'Allows updating tenant users with the Admin role.',
        'delete_admin_user' => 'Allows deleting tenant users with the Admin role.',
        'assign_admin_permissions' => 'Allows assigning permissions to tenant users with the Admin role.',
        'list_customer' => 'Allows viewing the tenant customer list.',
        'create_customer' => 'Allows creating tenant customers.',
        'delete_customer' => 'Allows flag-deleting tenant customers.',
        'update_customer' => 'Allows updating tenant customers.',
        'list_collateral' => 'Allows viewing the merged collateral item list.',
        'create_collateral' => 'Allows creating collateral items.',
        'update_collateral' => 'Allows updating collateral items.',
        'delete_collateral' => 'Allows deleting collateral items.',
        'list_accounting' => 'Allows viewing tenant accounting records.',
        'list_financial_account_type' => 'Allows viewing platform and tenant financial account types.',
        'create_financial_account_type' => 'Allows creating tenant financial account types.',
        'update_financial_account_type' => 'Allows updating tenant financial account types.',
        'delete_financial_account_type' => 'Allows deactivating tenant financial account types.',
        'list_expense' => 'Allows viewing tenant expense records.',
        'create_expense' => 'Allows creating tenant expense records.',
        'update_expense' => 'Allows updating tenant expense records.',
        'delete_expense' => 'Allows deleting tenant expense records.',
        'list_capital' => 'Allows viewing tenant capital records.',
        'create_capital' => 'Allows creating tenant capital records.',
        'update_capital' => 'Allows updating tenant capital records.',
        'delete_capital' => 'Allows deleting tenant capital records.',
        'list_debt' => 'Allows viewing tenant debt records.',
        'create_debt' => 'Allows creating tenant debt records.',
        'update_debt' => 'Allows updating tenant debt records.',
        'delete_debt' => 'Allows deleting tenant debt records.',
        'list_loan_contract' => 'Allows viewing loan contract slips.',
        'create_loan_contract' => 'Allows creating loan contract slips.',
        'delete_loan_contract' => 'Allows deleting loan contract slips.',
        'manage_slip_document' => 'Allows managing tenant slip document layout.',
        'list_currency' => 'Allows viewing platform and tenant currencies.',
        'create_currency' => 'Allows creating tenant currencies.',
        'update_currency' => 'Allows updating tenant currencies.',
        'delete_currency' => 'Allows deleting tenant currencies.',
        'list_exchange_pair' => 'Allows viewing exchange-rate pairs.',
        'create_exchange_pair' => 'Allows creating tenant exchange-rate pairs.',
        'update_exchange_pair' => 'Allows updating tenant exchange-rate pairs.',
        'delete_exchange_pair' => 'Allows deleting tenant exchange-rate pairs.',
        'list_exchange_rate' => 'Allows viewing exchange-rate history and OHLC.',
        'create_exchange_rate' => 'Allows recording tenant exchange rates.',
        'correct_exchange_rate' => 'Allows correcting tenant exchange rates.',
        'void_exchange_rate' => 'Allows voiding tenant exchange rates.',
        'manage_tenant_timezone' => 'Allows configuring the tenant business timezone.',
    ],
    'roles' => [
        'Owner' => [
            'description' => 'Tenant owner role with full access to tenant user management.',
            'is_default' => true,
            'permissions' => [
                'dashboard',
                'access_all',
                'create_admin_user',
                'update_admin_user',
                'delete_admin_user',
                'assign_admin_permissions',
            ],
        ],
        'Admin' => [
            'description' => 'Tenant administrator role with full access to tenant user management.',
            'is_default' => true,
            'permissions' => [
                'dashboard',
                'list_user',
                'create_user',
                'delete_user',
                'update_user_admin',
                'update_user_all',
                'update_user_own',
                'list_customer',
                'create_customer',
                'delete_customer',
                'update_customer',
                'list_collateral',
                'create_collateral',
                'update_collateral',
                'delete_collateral',
                'list_accounting',
                'list_financial_account_type',
                'create_financial_account_type',
                'update_financial_account_type',
                'delete_financial_account_type',
                'list_expense',
                'create_expense',
                'update_expense',
                'delete_expense',
                'list_capital',
                'create_capital',
                'update_capital',
                'delete_capital',
                'list_debt',
                'create_debt',
                'update_debt',
                'delete_debt',
                'list_loan_contract',
                'create_loan_contract',
                'delete_loan_contract',
                'manage_slip_document',
                'list_currency',
                'create_currency',
                'update_currency',
                'delete_currency',
                'list_exchange_pair',
                'create_exchange_pair',
                'update_exchange_pair',
                'delete_exchange_pair',
                'list_exchange_rate',
                'create_exchange_rate',
                'correct_exchange_rate',
                'void_exchange_rate',
                'manage_tenant_timezone',
            ],
        ],
        'User' => [
            'description' => 'Standard tenant user role with self-update, customer create, and full collateral item permissions.',
            'is_default' => true,
            'permissions' => [
                'update_user_own',
                'create_customer',
                'list_collateral',
                'create_collateral',
                'update_collateral',
                'delete_collateral',
                'list_loan_contract',
                'create_loan_contract',
                'list_currency',
                'list_financial_account_type',
                'list_exchange_pair',
                'list_exchange_rate',
            ],
        ],
    ],
];
