<?php

return [
    'codes' => [
        'dashboard' => 'Allows viewing the tenant dashboard summary.',
        'access_all' => 'Full tenant access.',
        'list_user' => 'Allows viewing the tenant user list.',
        'create_user' => 'Allows creating tenant users.',
        'delete_user' => 'Allows flag-deleting tenant users.',
        'update_user_admin' => 'Allows updating tenant user role and status.',
        'update_user_all' => 'Allows updating any tenant user profile information.',
        'update_user_own' => 'Allows updating only own tenant user profile information.',
        'list_customer' => 'Allows viewing the tenant customer list.',
        'create_customer' => 'Allows creating tenant customers.',
        'delete_customer' => 'Allows flag-deleting tenant customers.',
        'update_customer' => 'Allows updating tenant customers.',
        'list_collateral' => 'Allows viewing the merged collateral item list.',
        'create_collateral' => 'Allows creating collateral items.',
        'update_collateral' => 'Allows updating collateral items.',
        'delete_collateral' => 'Allows deleting collateral items.',
        'list_accounting' => 'Allows viewing tenant accounting records.',
        'list_expense' => 'Allows viewing tenant expense records.',
        'create_expense' => 'Allows creating tenant expense records.',
        'update_expense' => 'Allows updating tenant expense records.',
        'delete_expense' => 'Allows deleting tenant expense records.',
        'list_debt' => 'Allows viewing tenant debt records.',
        'create_debt' => 'Allows creating tenant debt records.',
        'update_debt' => 'Allows updating tenant debt records.',
        'delete_debt' => 'Allows deleting tenant debt records.',
        'list_loan_contract' => 'Allows viewing loan contract slips.',
        'create_loan_contract' => 'Allows creating loan contract slips.',
        'delete_loan_contract' => 'Allows deleting loan contract slips.',
        'manage_slip_document' => 'Allows managing tenant slip document layout.',
    ],
    'roles' => [
        'Owner' => [
            'description' => 'Tenant owner role with full access to tenant user management.',
            'is_default' => true,
            'permissions' => ['dashboard', 'access_all'],
        ],
        'Admin' => [
            'description' => 'Tenant administrator role with full access to tenant user management.',
            'is_default' => true,
            'permissions' => ['access_all'],
        ],
        'User' => [
            'description' => 'Standard tenant user role with self-update, customer create, and full collateral item permissions.',
            'is_default' => true,
            'permissions' => [
                'update_user_own',
                'create_customer',
                'list_collateral',
                'create_collateral',
                'update_collateral',
                'delete_collateral',
                'list_loan_contract',
                'create_loan_contract',
            ],
        ],
    ],
];
