<?php

namespace App\DataObjects\RequestObjects;

use App\DataObjects\BaseDataObject;
use App\Models\CoreModule\TenantCustomer;

class TenantCustomerCreate extends BaseDataObject
{
    public function __construct(
        public string $name,
        public ?string $nrc = null,
        public ?string $email = null,
        public ?string $phone = null,
        public ?string $address = null,
        public int $trustScore = TenantCustomer::DEFAULT_TRUST_SCORE,
        public ?string $note = null,
        public ?int $tenantId = null,
        public ?int $createdBy = null,
        public bool $isAutoGenerated = false,
    ) {
    }
}
